import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import Footer from './components/footer';
import Hero1 from './components/hero1';
import FooterTwo from './components/FooterTwo';
import { Providers } from './provider';
import SimpleFooter from './components/SimpleFooter';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`dark:bg-black ${inter.className}`}>
        <Providers>
          <Header />
          {children}
          <SimpleFooter />
        </Providers>
      </body>
    </html>
  );
}
